export const tasks = {
  zh: {
    luckyTasks: [
      {
        id: '43',
        titleTag: '抽奖任务',
        taskType: '3',
        taskName: '上海星梦剧场公演门票 x2',
        taskProfile: '谁是幸运儿？',
        description:
          '抽奖资格：注册MEET48账户，$PICK积分＞1000 即可参与本次抽奖。\r\n\r\n抽奖方式：\r\n点击下方按钮，提交个人信息。我们将从符合标准的用户中抽取2人赠送上海星梦剧场公演门票。\r\n\r\n抽奖报名时间：\r\n8月14日 00:00 - 8月28日 00:00\r\n\r\n开奖时间：\r\n8月31日 16:00\r\n\r\n获奖结果公布：\r\n我们将在Twitter @Meet_48 及 MEET48 QQ群公布获奖用户，请关注以下平台信息。',
        taskOpen: '1',
        reward: 0,
        taskStatus: false,
        taskTypePosition: 0,
        taskPosition: null,
        taskEndAt: '1693152000000',
        drawingTime: '1693468800000',
        taskCompletedStatus: null,
      },
      {
        id: '44',
        titleTag: '抽奖任务',
        taskType: '3',
        taskName: '乐啤酒社-啤酒体验券 x100',
        taskProfile: '盛夏降温计划',
        description:
          '抽奖资格：注册MEET48账户即可参与本次抽奖。\r\n\r\n抽奖方式：\r\n点击下方按钮，提交个人信息。我们将以先到先得的方式选取100人赠送乐啤酒社 MINTLAND 提供的啤酒体验权益。\r\n\r\n奖品说明：\r\n持有乐啤酒社 MINTLAND 提供的啤酒体验券的用户，可凭此券获得2项权益：\r\n【权益1】免费领取NFT定制生啤1杯\r\n【权益2】MEET48限定权益所有消费终身88折\r\n\r\n抽奖报名时间：\r\n8月14日 00:00 - 8月29日 00:00\r\n\r\n开奖时间：\r\n每日16:00通过先到先得方式发放\r\n\r\n获奖结果公布：\r\n我们将在Twitter @Meet_48 及 MEET48 QQ群公布获奖用户，请关注以下平台信息。',
        taskOpen: '1',
        reward: 0,
        taskStatus: false,
        taskTypePosition: 0,
        taskPosition: null,
        taskEndAt: '1693238400000',
        drawingTime: '1693324800000',
        taskCompletedStatus: null,
      },
    ],
    supportTasks: [
      {
        id: '1',
        titleTag: '打Call任务',
        taskType: '1',
        taskName: '每日领取$PICK积分\n',
        taskProfile: '每日上线领取$PICK积分',
        description:
          '每日上线通过做任务领取$PICK积分，积累的$PICK积分越多则未来兑换的打Call棒越多。您可以通过做任务来获取更多的$PICK积分哦！',
        taskOpen: '1',
        reward: 20,
        taskStatus: false,
        taskTypePosition: 1,
        taskPosition: 0,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '15',
        titleTag: '打Call任务',
        taskType: '2',
        taskName: '查看速报榜单\n',
        taskProfile: '查看第一阶段速报（6月25日）榜单数据。',
        description: '查看你 pick的偶像有没有上榜吧！',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 1,
        taskPosition: 3,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '35',
        titleTag: '打Call任务',
        taskType: '1',
        taskName: '每日随机小测验',
        taskProfile: '来测试河里知多少吧',
        description:
          '下列河里知识点你都知道哪些呢？来挑战一下吧 每次随机小测验将从题库中随机抽取5道题目，每答对一道题目可以获得10 $pick的奖励，答错/未作答将不得分。',
        taskOpen: '1',
        reward: 50,
        taskStatus: false,
        taskTypePosition: 1,
        taskPosition: 5,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '38',
        titleTag: '打Call任务',
        taskType: '2',
        taskName: '查看中报榜单',
        taskProfile: '查看第二阶段中报（7月16日）榜单。',
        description: '查看你 pick的偶像有没有上榜吧！',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 1,
        taskPosition: 4,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '42',
        titleTag: '打Call任务',
        taskType: '2',
        taskName: '查看终报榜单',
        taskProfile: '看看谁是C位！',
        description: 'TOP16排名已发布，来看看最终排名吧！\n榜单查询链接：',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 1,
        taskPosition: 6,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
    ],
    promotionalTasks: [
      {
        id: '2',
        titleTag: '安利任务',
        taskType: '3',
        taskName: '邀请好友一起打Call\n',
        taskProfile: '邀请好友注册，一名好友加入即可获得50积分奖励',
        description:
          '每成功邀请1位好友一起打call即可完成任务并获得50 $pick，邀请人数上不封顶。\n\n任务达成条件：\n1.好友通过邀请链接进入并注册账号；\n\n邀请奖励将于每日8 点统一发放。',
        taskOpen: '1',
        reward: 50,
        taskStatus: false,
        taskTypePosition: 2,
        taskPosition: 0,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '16',
        titleTag: '安利任务',
        taskType: '1',
        taskName: 'Weibo-超话活跃',
        taskProfile: '在偶像超话分享MEET48活动',
        description:
          '在偶像超话活跃，分享 MEET48 活动。\n\n要求：\n1.发布微博分享MEET48活动（可参考下方示例），微博中需包含MEET48网址\n2.发布后点击下方按钮提交微博截图\n\n参考语：\n一起领取SNH48 GROUP香港之行门票吧！\n完成MEET48网站任务即可获得积分，免费兑换门票哦～\n https://gipr.meet48.xyz/#/task\n\n积分发放时间：\n在表单中提交相关信息，等待工作人员审核，审核将在 24h 内完成。审核通过后将在次日 18：00发放积分。\n若一天内多次完成微博任务，积分奖励将会逐步发放，每天至多发放 3 次任务奖励积分，直至您的奖励积分发送完毕。',
        taskOpen: '1',
        reward: 40,
        taskStatus: false,
        taskTypePosition: 2,
        taskPosition: 2,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '30',
        titleTag: '安利任务',
        taskType: '3',
        taskName: 'Bilibili-评论视频',
        taskProfile: '在B 站评论区分享MEET48活动',
        description:
          '评论塞纳河相关的 B 站视频，分享 MEET48 活动。\n\n要求：\n1.发布评论分享MEET48活动（可参考下方示例），评论中需包含MEET48网址\n2.发布后点击下方按钮提交评论截图\n\n评论参考语：\n一起领取SNH48 GROUP香港之行门票吧！\n完成MEET48网站任务即可获得积分，免费兑换门票哦～\n https://gipr.meet48.xyz/#/task\n\n积分发放时间：\n在表单中提交评论截图，等待工作人员审核，审核将在 24h 内完成。审核通过后将在次日 18：00发放积分。\n若一天内多次完成评论任务，积分奖励将会逐步发放，每天至多发放 3 次任务奖励积分，直至您的奖励积分发送完毕。',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 2,
        taskPosition: 3,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '31',
        titleTag: '安利任务',
        taskType: '3',
        taskName: '小红书-分享活动',
        taskProfile: '在小红书分享MEET48活动',
        description:
          '在小红书分享 MEET48 活动。\n\n要求：\n1.发布小红书分享活动（可参考下方示例），其中笔记中的一张图片中需包含活动链接\n2.发布后点击下方按钮提交小红书截图\n\n参考语：\n一起领取SNH48 GROUP香港之行门票吧！\n完成MEET48网站任务即可获得积分，免费兑换门票哦～\n https://gipr.meet48.xyz/#/task\n网址在p2~\n\n积分发放时间：\n在表单中提交相关信息，等待工作人员审核，审核将在 24h 内完成。审核通过后将在次日 18：00发放积分。_x005f_x005f_x005f_x005f_x005f_x005f_x005f_x005f\u000b若一天内多次完成本任务，积分奖励将会逐步发放，每天至多发放 3 次任务奖励积分，直至您的奖励积分发送完毕。',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 2,
        taskPosition: 4,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '33',
        titleTag: '安利任务',
        taskType: '3',
        taskName: '社区-分享活动',
        taskProfile: '在应援团或其他河粉社区分享MEET48活动',
        description:
          '在应援团或其他河粉社区分享MEET48 活动。\r\n\r\n要求：\r\n1.分享内容需包含活动信息及活动链接 \r\n2.发布后点击下方按钮提交评论截图\r\n\r\n活动链接：\r\nhttps://gipr.meet48.xyz/\r\n\r\n积分发放时间：\r\n在表单中提交分享截图，等待工作人员审核，审核将在 24h 内完成。审核通过后将在次日 18：00发放积分。\r\n若一天内多次完成本任务，积分奖励将会逐步发放，每天至多发放 3 次任务奖励积分，直至您的奖励积分发送完毕。',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 2,
        taskPosition: 5,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '34',
        titleTag: '安利任务',
        taskType: '3',
        taskName: '线下-神秘福袋',
        taskProfile: '神秘的线下活动掉落的福袋',
        description:
          '一些神秘的线下活动掉落的指定福袋，很少出现。\r\n\r\n积分发放时间：\r\n在表单中提交分享截图，等待工作人员审核，审核将在 24h 内完成。审核通过后将在次日 18：00发放积分。',
        taskOpen: '1',
        reward: 100,
        taskStatus: false,
        taskTypePosition: 2,
        taskPosition: 6,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '37',
        titleTag: '安利任务',
        taskType: '3',
        taskName: '加入QQ社区',
        taskProfile: '加入Meet48 QQ社区，第一时间获取最新信息',
        description:
          '加入Meet48 QQ社群\r\n\r\nQQ群号：${qqGroupCode}\r\n或在页面最下方通过QQ二维码加入社群\r\n\r\n积分发放时间：\r\n在表单中提交进群截图，等待工作人员审核，审核将在 24h 内完成。审核通过后将在次日 18：00发放积分，入群任务每个账号仅能完成一次。',
        taskOpen: '1',
        reward: 50,
        taskStatus: false,
        taskTypePosition: 2,
        taskPosition: 1,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
    ],
    bindTasks: [
      {
        id: '5',
        titleTag: '绑定任务',
        taskType: '2',
        taskName: '绑定Twitter',
        taskProfile: '在个人信息绑定Twitter账号',
        description: '在个人信息绑定Twitter账号',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 3,
        taskPosition: 0,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '6',
        titleTag: '绑定任务',
        taskType: '2',
        taskName: '绑定Discord',
        taskProfile: '在个人信息绑定Discord账号',
        description: '在个人信息绑定Discord账号',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 3,
        taskPosition: 1,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '14',
        titleTag: '绑定任务',
        taskType: '2',
        taskName: '绑定邮箱',
        taskProfile: '绑定邮箱',
        description: '在个人信息绑定邮箱账号',
        taskOpen: '1',
        reward: 10,
        taskStatus: false,
        taskTypePosition: 3,
        taskPosition: 2,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
    ],
    twitterTasks: [
      {
        id: '8',
        titleTag: 'Twitter任务',
        taskType: '1',
        taskName: 'Twitter-转发最新情报',
        taskProfile: '转发最新推文',
        description: '在Twitter转发@meet_48的最新推文，${twitterStatusLink}',
        taskOpen: '1',
        reward: 20,
        taskStatus: false,
        taskTypePosition: 4,
        taskPosition: 1,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '9',
        titleTag: 'Twitter任务 ',
        taskType: '1',
        taskName: 'Twitter-评论最新情报',
        taskProfile: '评论最新推文',
        description:
          '在Twitter评论@meet_48的最新推文，并@2位好友${twitterStatusLink}',
        taskOpen: '1',
        reward: 20,
        taskStatus: false,
        taskTypePosition: 4,
        taskPosition: 2,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '10',
        titleTag: 'Twitter任务 ',
        taskType: '1',
        taskName: 'Twitter-点赞最新情报',
        taskProfile: '点赞最新推文',
        description: '在Twitter点赞@meet_48的最新推文${twitterStatusLink}',
        taskOpen: '1',
        reward: 20,
        taskStatus: false,
        taskTypePosition: 4,
        taskPosition: 3,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '11',
        titleTag: 'Twitter任务 ',
        taskType: '1',
        taskName: 'Twitter-发布应援推文',
        taskProfile: '在Twitter发布推文为你的偶像应援',
        description:
          '在Twitter发布应援推文@meet_48\n配文要求：\n1.@meet_48\n2.应援语+ #Idolverse #SNH48 #GIPR gipr.meet48.xyz',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 4,
        taskPosition: 4,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
    ],
    nftTasks: [],
    discordTasks: [
      {
        id: '13',
        titleTag: 'Discord任务',
        taskType: '2',
        taskName: 'Discord-加入社区',
        taskProfile: '加入我们的Discord社区',
        description: '加入Meet48官方Discord社区\n',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 5,
        taskPosition: 0,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '18',
        titleTag: 'Discord任务',
        taskType: '2',
        taskName: 'Discord-聊在一起',
        taskProfile: '成为社区聊天王',
        description:
          '在Discord活跃度达到Lv5，并获得 @Active 身份标签，在level-check频道，使用/rank命令，可以查看自己的聊天等级\nDiscord :  ${discordJoinLink}\n',
        taskOpen: '1',
        reward: 50,
        taskStatus: false,
        taskTypePosition: 5,
        taskPosition: 1,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
    ],
    visitingTasks: [
      {
        id: '23',
        titleTag: '浏览任务',
        taskType: '2',
        taskName: 'Bilibili-遇见Meet48',
        taskProfile: '访问一次B站上Meet48主页',
        description: '访问一次B站上Meet48主页',
        taskOpen: '1',
        reward: 10,
        taskStatus: false,
        taskTypePosition: 7,
        taskPosition: 0,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '25',
        titleTag: '浏览任务',
        taskType: '2',
        taskName: 'YouTube-访问频道',
        taskProfile: '访问Meet48的YouTube频道',
        description: '访问Meet48的YouTube频道',
        taskOpen: '1',
        reward: 10,
        taskStatus: false,
        taskTypePosition: 7,
        taskPosition: 1,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '36',
        titleTag: '浏览任务',
        taskType: '2',
        taskName: 'Bilibili-谁是卡牌擂主',
        taskProfile: '偶像卡牌大赛开播，上演C位之争',
        description:
          'MEET48偶像卡牌大赛正式开播啦！\r\nSNH48 TEAM X 做客第一期 MEET48 偶像卡牌大赛，上演C位之争，来看她们的精彩表现吧！\r\n\r\n偶像卡牌大赛 EP1 （上）（下）请在Meet48主页收看。',
        taskOpen: '1',
        reward: 20,
        taskStatus: false,
        taskTypePosition: 7,
        taskPosition: 2,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
    ],
    bilibiliTasks: [],
    youtubeTasks: [],
  },
  en: {
    luckyTasks: [
      {
        id: '43',
        titleTag: 'Lucky Task',
        taskType: '3',
        taskName: 'SNH48 Show Ticket x2',
        taskProfile: "Who's the lucky one?",
        description:
          'Eligibility:\r\nSign up for a MEET48 account with $PICK points > 1,000 to enter this sweepstakes.\r\n\r\nSweepstakes Method:\r\nClick the button below to submit information.\r\nWe will draw 2 people from those who meet the criteria to give away SNH48 show tickets.\r\n\r\nEnrollment Time:\r\nAugust 14th 00:00 - August 28th 00:00\r\n\r\nPrize Drawing Time:\r\nAugust 31st 16:00\r\n\r\nAnnouncement:\r\nWe will announce the winners on Twitter @Meet_48 and MEET48 QQ group, please follow the information.',
        taskOpen: '1',
        reward: 0,
        taskStatus: false,
        taskTypePosition: 0,
        taskPosition: null,
        taskEndAt: '1693152000000',
        drawingTime: '1693468800000',
        taskCompletedStatus: null,
      },
      {
        id: '44',
        titleTag: 'Lucky Task',
        taskType: '3',
        taskName: 'Le Beer Club - Beer Experience Voucher x100',
        taskProfile: 'Enjoy a beer night together!',
        description:
          'Eligibility:\r\nSign up for a MEET48 account to enter this sweepstakes.\r\n\r\nSweepstakes Method:\r\nClick the button below to submit information. 100 people will be selected on a FCFS basis to receive a beer experience courtesy of MINTLAND.\r\n\r\nPrize Description:\r\nHolders of the Beer Experience Coupon provided by MINTLAND will receive 2 entitlements with this coupon:\r\n1. Receive 1 glass of beer for free\r\n2. Lifetime 12% off on all purchases\r\n\r\nEnrollment Time:\r\nAugust 14th 00:00 - August 29th 00:00\r\n\r\nPrize Drawing Time:\r\nDistributed daily at 16:00 on a FCFS basis.\r\n\r\nAnnouncement:\r\nWe will announce the winners on Twitter @Meet_48 and MEET48 QQ group, please follow the information.',
        taskOpen: '1',
        reward: 0,
        taskStatus: false,
        taskTypePosition: 0,
        taskPosition: null,
        taskEndAt: '1693238400000',
        drawingTime: '1693324800000',
        taskCompletedStatus: null,
      },
    ],
    supportTasks: [
      {
        id: '1',
        titleTag: 'Support Task',
        taskType: '1',
        taskName: 'Collect PICK points (Daily)',
        taskProfile: 'Login to collect PICK points.',
        description:
          'You can collect PICK points by doing tasks!\n\nThe more PICK points you accumulate, the more you can exchange for future Cheering Sticks. \n\nGet ready for the next phase of boosting!',
        taskOpen: '1',
        reward: 20,
        taskStatus: false,
        taskTypePosition: 1,
        taskPosition: 0,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '15',
        titleTag: 'Support Task',
        taskType: '2',
        taskName: 'View List',
        taskProfile: 'View Idol Rankings.',
        description: 'View Idol Rankings.',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 1,
        taskPosition: 3,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '35',
        titleTag: 'Support Task',
        taskType: '1',
        taskName: 'Random Quizzes(Daily)',
        taskProfile: 'Test your knowledge of SNH48 GROUP.',
        description: 'Do you know all of these? Challenge yourself!',
        taskOpen: '1',
        reward: 50,
        taskStatus: false,
        taskTypePosition: 1,
        taskPosition: 5,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '38',
        titleTag: 'Support Task',
        taskType: '2',
        taskName: 'View List',
        taskProfile: 'View Idol Rankings.',
        description: 'View Idol Rankings.',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 1,
        taskPosition: 4,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '42',
        titleTag: 'Support Task',
        taskType: '2',
        taskName: 'View the final rankings',
        taskProfile: "Who's the champion?",
        description: 'Top 16 revealed, check out the final rankings!\nLink:',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 1,
        taskPosition: 6,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
    ],
    promotionalTasks: [
      {
        id: '2',
        titleTag: 'Promotional Task',
        taskType: '3',
        taskName: 'Invite Friends',
        taskProfile:
          'Invite your friends to register and get 50 PICK points when one friend joins.',
        description:
          'Each time you successfully invite your friends to register, you can get a bonus of 50 $PICK per person, and there is no limit to the number of people you can invite.\nInvitation Link:\n\nDescription:\n1.Someone has successfully registered an account through your invitation link.\n\nRewards will be given out daily at 8am.',
        taskOpen: '1',
        reward: 50,
        taskStatus: false,
        taskTypePosition: 2,
        taskPosition: 0,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '16',
        titleTag: 'Promotional Task',
        taskType: '3',
        taskName: 'Share events on Weibo',
        taskProfile: 'Share MEET48 Events on Weibo.',
        description:
          'Requirements:\n1. Post the canvassing content on Weibo (refer to the example below), the content should contain your invitation event URL. \n2. Click the button below to submit a screenshot after posting\n\nExample:\nCome and get your SNH48 GROUP Hong Kong show tickets!\nYou can earn points by completing tasks on MEET48 website and redeem the tickets for free!\n https://gipr.meet48.xyz/#/task\n\nReward distribution time:\nSubmit the relevant information in the form and wait for the review, the staff will complete the review within 24h. Points will be issued at 18:00 on the next day after the review.\nIf you complete this task several times in a day, the reward points will be issued gradually, up to 3 times a day, until your reward points are sent out.',
        taskOpen: '1',
        reward: 40,
        taskStatus: false,
        taskTypePosition: 2,
        taskPosition: 2,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '30',
        titleTag: 'Promotional Task',
        taskType: '3',
        taskName: 'Post comments on Bilibili',
        taskProfile: 'Share MEET48 Events on Bilibili.',
        description:
          'Requirements:\n1. Post a canvassing comment (refer to the example below), the comment should contain your invitation event URL.\n2. Click the button below to submit a screenshot of your comment after posting\n\nExample:\nCome and get your SNH48 GROUP Hong Kong show tickets!\nYou can earn points by completing tasks on MEET48 website and redeem the tickets for free!\n https://gipr.meet48.xyz/#/task\n\nReward distribution time:\nSubmit the relevant information in the form and wait for the review, the staff will complete the review within 24h. Points will be issued at 18:00 on the next day after the review.\nIf you complete this task several times in a day, the reward points will be issued gradually, up to 3 times a day, until your reward points are sent out.',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 2,
        taskPosition: 3,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '31',
        titleTag: 'Promotional Task',
        taskType: '3',
        taskName: 'Share events on XiaoHongShu',
        taskProfile: 'Share MEET48 Events on XiaoHongShu.',
        description:
          'Requirements:\n1. Post the canvassing content on XiaoHongShu (refer to the example below), the content should contain event URL.\n2. Click the button below to submit a screenshot after posting\n\nExample:\nCome and get your SNH48 GROUP Hong Kong show tickets!\nYou can earn points by completing tasks on MEET48 website and redeem the tickets for free!\n https://gipr.meet48.xyz/#/task\nURL at p2~\n\n\nReward distribution time:\nSubmit the relevant information in the form and wait for the review, the staff will complete the review within 24h. Points will be issued at 18:00 on the next day after the review.\nIf you complete this task several times in a day, the reward points will be issued gradually, up to 3 times a day, until your reward points are sent out.',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 2,
        taskPosition: 4,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '33',
        titleTag: 'Promotional Task',
        taskType: '3',
        taskName: 'Share events in the community',
        taskProfile: 'Share events in the SNH48 GROUP fans community.',
        description:
          'Requirements:\n1.Share the content with the event information and the link of the event website \n2. Click the button below to submit a screenshot after posting\n\nWebsite:\nhttps://gipr.meet48.xyz/\n\nReward distribution time:\nSubmit the relevant information in the form and wait for the review, the staff will complete the review within 24h. Points will be issued at 18:00 on the next day after the review.\nIf you complete this task several times in a day, the reward points will be issued gradually, up to 3 times a day, until your reward points are sent out.',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 2,
        taskPosition: 5,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '34',
        titleTag: 'Promotional Task',
        taskType: '3',
        taskName: 'Mystery Lucky Bag',
        taskProfile: 'Gifts dropped by offline activities.',
        description:
          'Gifts dropped by offline activities.\r\n\r\nReward distribution time:\r\nSubmit the relevant information in the form and wait for the review, the staff will complete the review within 24h. Points will be issued at 18:00 on the next day after the review.',
        taskOpen: '1',
        reward: 100,
        taskStatus: false,
        taskTypePosition: 2,
        taskPosition: 6,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '37',
        titleTag: 'Promotional Task',
        taskType: '3',
        taskName: 'Join QQ Community',
        taskProfile: 'Join the Meet48 QQ community.',
        description:
          "Join the Meet48 QQ Community\r\n\r\nQQ Group ID:${qqGroupCode} \r\nAlternatively, you can join the community by scanning the QQ QR code at the bottom of the page.\r\n\r\nPoints Distribution Schedule:\r\nSubmit a screenshot of joining the group in the form and wait for the staff's review. The review process will be completed within 24 hours. Once approved, points will be distributed at 18:00 the following day. Each account can only complete the joining task once.",
        taskOpen: '1',
        reward: 50,
        taskStatus: false,
        taskTypePosition: 2,
        taskPosition: 1,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
    ],
    bindTasks: [
      {
        id: '5',
        titleTag: 'Account Task',
        taskType: '2',
        taskName: 'Add Twitter account',
        taskProfile: 'Add a Twitter account to your profile.',
        description: 'Add a Twitter account to your profile.',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 3,
        taskPosition: 0,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '6',
        titleTag: 'Account Task',
        taskType: '2',
        taskName: 'Add Discord account',
        taskProfile: 'Add a Discord account to your profile.',
        description: 'Add a Discord account to your profile.',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 3,
        taskPosition: 1,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '14',
        titleTag: 'Account Task',
        taskType: '2',
        taskName: 'Binding Email',
        taskProfile: 'Add email to profile.',
        description: 'Add email to profile.',
        taskOpen: '1',
        reward: 10,
        taskStatus: false,
        taskTypePosition: 3,
        taskPosition: 2,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
    ],
    twitterTasks: [
      {
        id: '8',
        titleTag: 'Twitter Task',
        taskType: '1',
        taskName: 'Retweet',
        taskProfile: 'Retweet the latest tweets.',
        description: 'Retweet the latest tweets.${twitterStatusLink}',
        taskOpen: '1',
        reward: 20,
        taskStatus: false,
        taskTypePosition: 4,
        taskPosition: 1,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '9',
        titleTag: 'Twitter Task',
        taskType: '1',
        taskName: 'Comment',
        taskProfile: 'Comment on the latest tweets.',
        description:
          'Comment on the latest tweets , tag 2 friends.${twitterStatusLink}',
        taskOpen: '1',
        reward: 20,
        taskStatus: false,
        taskTypePosition: 4,
        taskPosition: 2,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '10',
        titleTag: 'Twitter Task',
        taskType: '1',
        taskName: 'Like Tweet',
        taskProfile: 'Like the latest tweets.',
        description: 'Like the latest tweets.${twitterStatusLink}',
        taskOpen: '1',
        reward: 20,
        taskStatus: false,
        taskTypePosition: 4,
        taskPosition: 3,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '11',
        titleTag: 'Twitter Task',
        taskType: '1',
        taskName: 'Post Tweets',
        taskProfile: 'Support your idols by tweeting on Twitter.',
        description:
          'Support your idols by tweeting on Twitter.  Requirements : a.Post tweet@meet_48 b.Add hashtag #Idolverse  #SNH48 #GIPR',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 4,
        taskPosition: 4,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
    ],
    nftTasks: [],
    discordTasks: [
      {
        id: '13',
        titleTag: 'Discord Task',
        taskType: '2',
        taskName: 'Join Discord',
        taskProfile: 'Join our Discord community.',
        description: 'Join Discord.',
        taskOpen: '1',
        reward: 30,
        taskStatus: false,
        taskTypePosition: 5,
        taskPosition: 0,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '18',
        titleTag: 'Discord Task',
        taskType: '2',
        taskName: 'Chat with frenz',
        taskProfile: 'Become a Community Influencer',
        description:
          'Join our Discord community! ${discordJoinLink}\nReaching level 5 and get @Active tags in our Discord.',
        taskOpen: '1',
        reward: 50,
        taskStatus: false,
        taskTypePosition: 5,
        taskPosition: 1,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
    ],
    visitingTasks: [
      {
        id: '23',
        titleTag: 'Visiting Task',
        taskType: '2',
        taskName: 'Visit Bilibili channel',
        taskProfile: "Visit Meet48's Bilibili channel once.",
        description: "Visit Meet48's Bilibili channel once.",
        taskOpen: '1',
        reward: 10,
        taskStatus: false,
        taskTypePosition: 7,
        taskPosition: 0,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '25',
        titleTag: 'Visiting Task',
        taskType: '2',
        taskName: 'Visit Youtube channel',
        taskProfile: "Visit Meet48's Youtube channel once.",
        description: "Visit Meet48's Youtube channel once.",
        taskOpen: '1',
        reward: 10,
        taskStatus: false,
        taskTypePosition: 7,
        taskPosition: 1,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
      {
        id: '36',
        titleTag: 'Visiting Task',
        taskType: '2',
        taskName: 'View Idol Card Competition',
        taskProfile: 'Idol Card Competition have started broadcasting.',
        description:
          'Meet48 recently started an idol card show called Idol Card Competition.\r\nThe first guest is SNH48 TEAMX.',
        taskOpen: '1',
        reward: 20,
        taskStatus: false,
        taskTypePosition: 7,
        taskPosition: 2,
        taskEndAt: null,
        drawingTime: null,
        taskCompletedStatus: null,
      },
    ],
    bilibiliTasks: [],
    youtubeTasks: [],
  },
};
