-- CreateTable
CREATE TABLE "qtn" (
    "id" BIGSERIAL NOT NULL,
    "tel" BIGINT,
    "A1" TEXT,
    "A2" TEXT,
    "A3" TEXT,
    "A4" BIGINT,
    "A5" TEXT,
    "A6" TEXT,
    "A7" TEXT,
    "A8" BIGINT,
    "A9" TEXT,
    "A10" TEXT,
    "B1" TEXT,
    "B2" TEXT,
    "B3" TEXT,
    "B4" TEXT,
    "B5" TEXT,
    "B6" TEXT,
    "B7_1" TEXT,
    "B7_2" TEXT,
    "B7_3" TEXT,
    "B7_4" TEXT,
    "B7_5" TEXT,
    "B7_6" TEXT,
    "B8_1" TEXT,
    "B8_2" TEXT,
    "B8_3" TEXT,
    "B8_4" TEXT,
    "B8_5" TEXT,
    "B8_6" TEXT,
    "B8_7" TEXT,
    "B8_8" TEXT,
    "B8_9" TEXT,
    "B8_10" TEXT,
    "C1" TEXT,
    "C2" TEXT,
    "C3" TEXT,
    "C4" TEXT,
    "C5" TEXT,
    "C6" TEXT,
    "C7" TEXT,
    "C8" TEXT,
    "C9" TEXT,
    "C10" TEXT,
    "C11" TEXT,
    "C12" TEXT,
    "C13" TEXT,
    "C14" TEXT,
    "D1_1" TEXT,
    "D1_2" TEXT,
    "D1_3" TEXT,
    "D1_4" TEXT,
    "D1_5" TEXT,
    "D1_6" TEXT,
    "D1_7" TEXT,
    "D1_8" TEXT,
    "D1_9" TEXT,
    "D1_10" TEXT,
    "D1_11" TEXT,
    "D1_12" TEXT,
    "D1_13" TEXT,
    "D1_14" TEXT,
    "D2_1" TEXT,
    "D2_2" TEXT,
    "D2_3" TEXT,
    "D2_4" TEXT,
    "D2_5" TEXT,
    "D2_6" TEXT,
    "D2_7" TEXT,
    "D2_8" TEXT,
    "D2_9" TEXT,
    "D2_10" TEXT,
    "D3" TEXT,
    "D4" TEXT,
    "D5" TEXT,
    "D6" TEXT,
    "D7" TEXT,

    CONSTRAINT "qtn_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Commits" (
    "id" BIGSERIAL NOT NULL,
    "cid" TEXT NOT NULL,
    "author_email" TEXT,
    "author_name" TEXT,
    "authored_date" TIMESTAMPTZ(6),
    "committed_date" TIMESTAMPTZ(6),
    "committer_email" TEXT,
    "committer_name" TEXT,
    "created_at" TIMESTAMPTZ(6),
    "title" TEXT,
    "message" TEXT,
    "project_id" BIGINT,
    "short_id" TEXT,
    "stats_additions" BIGINT,
    "stats_deletions" BIGINT,
    "stats_total" BIGINT,
    "status" TEXT,

    CONSTRAINT "Commit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Projects" (
    "id" INTEGER NOT NULL,
    "pid" INTEGER NOT NULL,
    "name" VARCHAR(500),
    "description" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(6),
    "updateAt" TIMESTAMPTZ(6),

    CONSTRAINT "Projects_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "qtn_id_key" ON "qtn"("id");

